steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/mystical-melody-486113-p0/cloud-run-source-deploy/mystical-melody-486113-p0:latest'
      - '-f'
      - 'backend/Dockerfile'
      - './backend'
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/mystical-melody-486113-p0/cloud-run-source-deploy/mystical-melody-486113-p0:latest'
images:
  - 'asia-south1-docker.pkg.dev/mystical-melody-486113-p0/cloud-run-source-deploy/mystical-melody-486113-p0:latest'
