steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/mystical-melody-486113-p0/cloud-run-source-deploy/sales-intelligence:latest'
      - '-f'
      - 'backend/Dockerfile'
      - '.'

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/mystical-melody-486113-p0/cloud-run-source-deploy/sales-intelligence:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sales-intelligence'
      - '--image=asia-south1-docker.pkg.dev/mystical-melody-486113-p0/cloud-run-source-deploy/sales-intelligence:latest'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'

images:
  - 'asia-south1-docker.pkg.dev/mystical-melody-486113-p0/cloud-run-source-deploy/sales-intelligence:latest'
